name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Generate Pages
        run: npm run generate
        # set baseURL to repository name [condorhero.me]
        # https://v3.nuxtjs.org/api/composables/use-runtime-config#appbaseurl
        env:
          NUXT_APP_BASE_URL: /${{ github.event.repository.name }}

      # https://github.com/vercel/next.js/issues/2029
      - name: Add .nojekyll file
        run: touch .output/public/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: .output/public/
